services:
  - type: web
    name: aeiron-unified-service
    env: python
    plan: starter
    region: oregon
    autoDeploy: true

    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"

    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
